### ISSUE TITLE
Share also sensor names (and bg images)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#108]
Currently sharee doesn't see custom names and background images owner of the sensors may have adjusted before/after sharing the sensors to someone else. We agreed earlier that due to privacy reasons at least bg photos should not be shared but now when I'm actually using the sharing feature and I'm sharing several sensors to my friend, I noticed that at least the names should be shared or otherwise sharee receives just multiple random sensors and he has no idea what they are.

Earlier we agreed also that sharee should be able to adjust names and bg images of the shared sensors. But this is in many cases unnecessary. After all, owner of the sensors has already installed and named and adjusted bg images of the sensors to match with their actual locations and sharee would not necessarily need to be able to adjust those again.

Let's discuss. Do you agree or disagree?

**Comment by ojousima** [comment]
> I noticed that at least the names should be shared

Agree, I think the picture could be also shared as the user makes a decision to share the picture. It's more important to not let anyone else see the shared pics.

> Earlier we agreed also that sharee should be able to adjust names and bg images of the shared sensors. But this is in many cases unnecessary. After all, owner of the sensors has already installed and named and adjusted bg images of the sensors to match with their actual locations and sharee would not necessarily need to be able to adjust those again.

This is a discussion about sharing: is it read-only or read-write? I think both have pros and cons, and good arguments can be made for both. I'd say that we can leave the share as read-write and add read-only sharing on todo if we start getting requests for the feature.

**Comment by laurijamsa** [comment]
I've now discussed about sharing with a few friends and other Ruuvi Station users and all of them think that background images and names should be definitely shared by default. I agree. Let's do it.

I agree also with keeping the read-write functionality that has been already implemented.

**Comment by laurijamsa** [comment]
On Slack:

Sami: I just deployed the "use owner's sensor name by default" (and allow overriding) and some alerting fixes. Let me know if you see anything peculiar.

Lauri: I tested it and it doesn’t work for me. Same experience than before: MAC address is shared as a name and no background image is shared. Tested to share using iOS app and checked the result with web app and Android app

**Comment by markoaamunkajo** [comment]
Issue still exists for me.
User aamunkajom@gmail.com shared sensor F1:AE:FE:68:4F:7B with name "Home Outside 😎" and background image to user marko@aamunkajo.com. Sensor is synced from network but no name or bg is shared.

**Comment by markoaamunkajo** [comment]
Same, name and background are not shared.

**Comment by Muhwu** [comment]
@markoaamunkajo Is this an issue on the e-mail, the ui or the mobile app? I've confirmed that the queries used to fetch the data from the API would show up the name and background for the other user as well, but perhaps there's some section of the code that does this wrong.

**Comment by markoaamunkajo** [comment]
@Muhwu Share happens in mobile app (iOS) no sensor name or bg showing for recipient in Android app or web app.
